### PR TITLE
Workflows steps replays on error

### LINKED ISSUE #753: Workflows steps replays on error
**As:** a user
**I want to:** be able to replay some failed steps in a workflow
**So that:** I can retry errors due to temporary issues (these errors at the end of a very long workflow are really frustrating...) 

**AC1:** Implementation should follow the consensus found in the related [architecture decision record](https://github.com/ystia/yorc/wiki/%5BDesign%5D-Workflows-steps-replays-on-error)
**AC2:** Should be made available through the CLI

### PR DESCRIPTION
**Pull request by loicalbertin**
# Pull Request description

## Description of the change

This PR enable the feature of replaying steps in error.

### What I did

* Updated documentation of the API endpoint to update a step state (most of the work was already done but not documented)
* Allow step state modification from error to initial
* Deprecate the 'yorc dep tasks fix' command
* Add a new 'yorc dep tasks update-step-state' command
* Fix resume issue by deleting .cancelFlag & .errorFlag on task when resuming it

### How to verify it

The easiest way to test it is to simulate a network connectivity issue when provisioning an infrastructure resource or submitting a job. VPNs may help here :smile:. 
Then you should use the new command `yorc dep tasks update-step-state <depID> <taskID> <stepName> initial` to set the step state to initial and finally resume the tasks using `yorc dep tasks resume <depID> <taskID>`.

### Description for the changelog

* Workflows steps replays on error  ([GH-753](https://github.com/ystia/yorc/issues/753))

## Applicable Issues

Fixes #753

### CODE REVIEW

File: commands/deployments/tasks/dep_update_task_step_state.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+	statusStr = strings.ToLower(statusStr)
+
+	// Safety check
+	_, err = tasks.ParseTaskStepStatus(statusStr)
+	if err != nil {
+		httputil.ErrExit(err)
+	}
+
+	// The task step status is set to "done"
```
Comment (laurentganne) [inline commands/deployments/tasks/dep_update_task_step_state.go:49]: Maybe remove the comment: the task step status is set to done or initial depending on the argument value

File: commands/deployments/tasks/dep_update_task_step_state_test.go [hunk 2]
```diff
@@ -0,0 +1,60 @@
+// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
```
Comment (laurentganne) [inline commands/deployments/tasks/dep_update_task_step_state_test.go:1]: Copyright 2021 :-)

**Review by laurentganne — APPROVED** [review]
Excellent! 👍

File: commands/deployments/tasks/dep_update_task_step_state.go (hunk 1 above)
Comment (loicalbertin) [inline commands/deployments/tasks/dep_update_task_step_state.go:49]:
```suggestion
```

Comment (loicalbertin) [reply commands/deployments/tasks/dep_update_task_step_state.go:49]: Right! Copy/Paste error let remove it

File: commands/deployments/tasks/dep_update_task_step_state_test.go (hunk 2 above)
Comment (loicalbertin) [reply commands/deployments/tasks/dep_update_task_step_state_test.go:1]: Copy/paste again, thx!

```suggestion
// Copyright 2021 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
```

File: commands/deployments/tasks/dep_update_task_step_state.go [hunk 3]
```diff
@@ -0,0 +1,83 @@
+// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
```
Comment (loicalbertin) [inline commands/deployments/tasks/dep_update_task_step_state.go:1]:
```suggestion
// Copyright 2021 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
```
