### PR TITLE
Bugfix/gh 417 non existent step

### LINKED ISSUE #417: Invalid memory address panic appends on a workflow with non-existent on success step reference
# Bug Report

## Description
Invalid memory address panic appends on a workflow with non-existent on success step reference

## Expected behavior
Explicit error describing the workflow issue
## Actual behavior
runtime error: invalid memory address or nil pointer dereference

## Priority

High

### PR DESCRIPTION
**Pull request by stebenoist**
# Pull Request description

## Description of the change
- Check if referenced wf step exist
- Return error when step doesn't exist 

### Description for the changelog
* Invalid memory address panic appends on a workflow with non-existent on success step reference ([GH-417](https://github.com/ystia/yorc/issues/417))
## Applicable Issues
fixes #417

### CODE REVIEW

File: tasks/workflow/builder/builder.go [hunk 1]
```diff
@@ -99,7 +99,12 @@ func setCancelPath(s *Step) {
 }
 
 func buildStepFromWFStep(kv *api.KV, deploymentID, wfName, stepName string, wfSteps map[string]*tosca.Step, visitedMap map[string]*visitStep) (*Step, error) {
-	wfStep := wfSteps[stepName]
+	var wfStep *tosca.Step
+	var ok bool
+	if wfStep, ok = wfSteps[stepName]; !ok {
```
Comment (loicalbertin) [inline tasks/workflow/builder/builder.go]:
```suggestion
	if wfStep, ok := wfSteps[stepName]; !ok {
```

Comment (stebenoist) [reply tasks/workflow/builder/builder.go]: Hum...but wfStep is a new locale var to the if bloc (declared and not used) except if I am wrong ?

Comment (loicalbertin) [reply tasks/workflow/builder/builder.go]: Yep you are right
