### PR TITLE
Fix BadAccess error in deployments.resolveValueAssignment

### LINKED ISSUE #526: deployments.resolveValueAssignment throws BadAccess if value can't be resolved
During writing a test that includes a relationship which includes a `get_attribute` reference I got a bad access error due to the attribute not being found.

## Expected behavior
No bad access error

## Actual behavior
Bad access error is thrown

## Steps to reproduce the issue
I assume referencing an attribute that is not set and doesn't have a default value with the `get_attribute` function should trigger it.

## Priority
Low

I'm creating this Issue just for completeness, the fix is very obvious.

### PR DESCRIPTION
**Pull request by schrej**
This fixes a BadAccess error by passing the passed valueAssignment to the log call instead of a null pointer.
As the variable is checked for nil two lines above, this is very likely to be a typo.

fixes #526

### CODE REVIEW

File: deployments/resolver.go [hunk 1]
```diff
@@ -336,7 +336,7 @@ func resolveValueAssignment(kv *api.KV, deploymentID, nodeName, instanceName, re
 	}
 	if valueAssignment == nil {
 		ctx := events.NewContext(context.Background(), events.LogOptionalFields{events.NodeID: nodeName, events.InstanceID: instanceName})
-		events.WithContextOptionalFields(ctx).NewLogEntry(events.LogLevelWARN, deploymentID).Registerf("[WARNING] The value assignment %q hasn't be resolved for deployment: %q, node: %q, instance: %q. An empty string is returned instead", valueAssignment, deploymentID, nodeName, instanceName)
+		events.WithContextOptionalFields(ctx).NewLogEntry(events.LogLevelWARN, deploymentID).Registerf("[WARNING] The value assignment %q hasn't be resolved for deployment: %q, node: %q, instance: %q. An empty string is returned instead", va, deploymentID, nodeName, instanceName)
```
Comment (schrej) [inline deployments/resolver.go]: the passed value assignment is parsed into `va` in line [328](https://github.com/ystia/yorc/pull/527/files#diff-434b86138c68a6e888c5e9568619124fR328)
