### PR TITLE
Bugfix/gh 324 add ctx props to events

### LINKED ISSUE #324: Custom command events doesn't provide enough information
# Issue Type

Put an X between the brackets of the corresponding issue type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description
Custom command events doesn't provide any information about nodeID, operationName.
However, this information is present in the context.
Overall, I wonder why we don't retrieve information from context in all event publications.

## Priority

Medium

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

### PR DESCRIPTION
**Pull request by stebenoist**
# Pull Request description

### What I did
1. Use the context to build event information for all events
2. Emit event on status change when related task status is updated
3. Add more information on operation and node name in case of custom command
4. add this information in events CLI

### How to verify it
Deploy the python component and execute custom commands say_hello/say_goofbye
(https://github.com/ystia/yorc-a4c-plugin/tree/develop/tosca-samples/org/ystia/yorc/samples/python)
Check with CLI (yorc d events -b) that operation name and node are present in the custom command related events

### Description for the changelog
* Custom command events doesn't provide enough information ([GH-324](https://github.com/ystia/yorc/issues/324))
## Applicable Issues
fixes #324

### CODE REVIEW

File: prov/ansible/execution.go [hunk 1]
```diff
@@ -61,6 +61,7 @@ host_key_checking=False
 timeout=30
 stdout_callback = yaml
 retry_files_save_path = #PLAY_PATH#
+nocows = 1
```
Comment (loicalbertin) [inline prov/ansible/execution.go]: Hum looks like very depend to your env :laughing:

File: tasks/workflow/task_execution.go [hunk 2]
```diff
@@ -180,8 +181,18 @@ func setTaskStatus(kv *api.KV, taskID string, status tasks.TaskStatus, lastIndex
 	}
 	if !set {
 		log.Debugf("[WARNING] Failed to set task status to:%q for taskID:%q as last index has been changed before. Retry it", status.String(), taskID)
-		return checkAndSetTaskStatus(kv, taskID, status)
+		return checkAndSetTaskStatus(ctx, kv, targetID, taskID, status)
 	}
+
+	// Emit event for status change
+	// As task has been set, error are ignored
+	wfName, _ := tasks.GetTaskData(kv, taskID, "workflowName")
```
Comment (loicalbertin) [inline tasks/workflow/task_execution.go]: What will happen if wfName is empty (in case of error silently bypassed)?

File: prov/ansible/execution.go (hunk 1 above)
Comment (stebenoist) [reply prov/ansible/execution.go]: Yep, but we don't support cows in Ansible stdout handler. And in some distribs, I'm afraid it's the default behavior ?
So let's disable it.

File: tasks/workflow/task_execution.go (hunk 2 above)
Comment (stebenoist) [reply tasks/workflow/task_execution.go]: wfName may be empty as this data is not filled for non-workflow task type (as for custom command by instance)

Comment (stebenoist) [reply tasks/workflow/task_execution.go]: I add some comments

File: prov/ansible/execution.go (hunk 1 above)
Comment (loicalbertin) [reply prov/ansible/execution.go]: That's a pity but ok :smiley:

File: tasks/workflow/task_execution.go (hunk 2 above)
Comment (loicalbertin) [reply tasks/workflow/task_execution.go]: Sounds good.

**Comment by loicalbertin** [comment]
Code review : LGTM
