### PR TITLE
Fix public_ip_address setting fro hostspool compute

### LINKED ISSUE #593: Tosca public_ip_address attribute is wrongly set with private address for hosts pool computes
# Bug Report

## Description

Tosca public_ip_address attribute is wrongly set with private address for hosts pool computes

### PR DESCRIPTION
**Pull request by stebenoist**
# Pull Request description

### Description for the changelog
Tosca public_ip_address attribute is wrongly set with private address for hosts pool computes ([GH-593](https://github.com/ystia/yorc/issues/593))
## Applicable Issues

fixes #593

### CODE REVIEW

File: prov/hostspool/executor_test.go [hunk 1]
```diff
@@ -266,6 +285,8 @@ func prepareTestEnv(t *testing.T, srv *testutil.TestServer, cc *api.Client, loca
 		"os.type":                 "linux",
 		"label1":                  "stringvalue1",
 		"public_address":          "1.2.3.4", // to cover some code using this resource
+		"public_ip_address":       "1.2.3.4",
+		"private_address":       "5.6.7.8",
```
Comment (loicalbertin) [inline prov/hostspool/executor_test.go]: looks like gofmt is missing.

Comment (stebenoist) [reply prov/hostspool/executor_test.go]: true !
