### PR TITLE
move actionOperator not shareable fields into another struct

### LINKED ISSUE #308: Slurm job monitoring is not designed for concurrency
# Issue Type

Put an X between the brackets of the corresponding issue type

* [X ] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description
actionOperator is a singleton used by all asynchronous operations but many struct fields are related to an action and not shareable by all.

### PR DESCRIPTION
**Pull request by stebenoist**
# Pull Request description

## Description of the change
Move actionOperator not shareable fields into another struct

## Applicable Issues
fixes #308

### CODE REVIEW

File: prov/slurm/actions.go [hunk 1]
```diff
@@ -44,7 +46,7 @@ type actionOperator struct {
 	outputs             []string
 }
 
-func (o actionOperator) ExecAction(ctx context.Context, cfg config.Configuration, taskID, deploymentID string, action *prov.Action) (bool, error) {
+func (o *actionOperator) ExecAction(ctx context.Context, cfg config.Configuration, taskID, deploymentID string, action *prov.Action) (bool, error) {
 	log.Debugf("Execute Action:%+v with taskID:%q, deploymentID:%q", action, taskID, deploymentID)
 	var err error
 	o.client, err = GetSSHClient(cfg)
```
Comment (loicalbertin) [inline prov/slurm/actions.go]:
```suggestion
	if o.client == nil {
		o.client, err = GetSSHClient(cfg)
	}
```

Could be done only once otherwise we can have some issues

Comment (loicalbertin) [reply prov/slurm/actions.go]: Same should be for `consulClient`

Comment (stebenoist) [reply prov/slurm/actions.go]: Yes, my bad...
