### PR TITLE
Bugfix release/4.0 Job sched termination

### LINKED ISSUE #677: Asynchronous execution termination detection error
# Bug Report

## Description

Fix for issue #659 introduced a bug that causes workflows to stop processing after an asynchronous operation.

This impacts Yorc 4.0.2 and net yet released Yorc 4.1.0-milestone.1

### PR DESCRIPTION
**Pull request by loicalbertin**
# Pull Request description

## Description of the change

Fix a regression introduced in PR #661 for fixing issue #659

### What I did

Fix wrong task ID used to compute running execution for a task.
In a scheduled action we should check for the workflow taskID and not the action taskID.

Also I activated some jobs tests to run in CI automatically.

### Description for the changelog

* Asynchronous execution termination detection error ([GH-677](https://github.com/ystia/yorc/issues/677))

## Applicable Issues

Fixes #677 
Ported to  develop (4.1.0-milestone.1 snapshot) in #679

### CODE REVIEW

File: tasks/workflow/step.go [hunk 1]
```diff
@@ -348,7 +348,8 @@ func (s *step) runActivity(wfCtx context.Context, cfg config.Configuration, depl
 				action.AsyncOperation.WorkflowStepInfo = eventInfo
 				// Register scheduled action for asynchronous execution
 				id, err := scheduling.RegisterAction(w.consulClient, deploymentID, timeInterval, action)
-				log.Debugf("Scheduled action with ID;%q has been registered with timeInterval:%s and ID:%q", action.ID, timeInterval.String(), id)
+				action.ID = id
+				log.Debugf("Scheduled action with ID: %q has been registered with timeInterval: %s", action.ID, timeInterval.String(), id)
```
Comment (loicalbertin) [inline tasks/workflow/step.go:352]:
```suggestion
				log.Debugf("Scheduled action with ID: %q has been registered with timeInterval: %s", action.ID, timeInterval.String())
```

**Review by laurentganne — APPROVED** [review]
Looks good! 👍
