### PR TITLE
Fix ES Store behaviour when ES in unreachable

### LINKED ISSUE #719: Yorc panics on ElasticSearch store error
When Yorc is configured to use ElasticSearch as store for logs and ElasticSearch becomes unreachable, yorc panics.
The stack trace shows:

```
 Mar 16 16:52:14 peaalx1038 yorc: panic: runtime error: invalid memory address or nil pointer dereference
Mar 16 16:52:14 peaalx1038 yorc: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc39137]
Mar 16 16:52:14 peaalx1038 yorc: goroutine 215 [running]:
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/storage/internal/elastic.closeResponseBody(0xc000a365d0, 0x22, 0x0)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/storage/internal/elastic/es_utils.go:302 +0x37
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/storage/internal/elastic.(*elasticStore).Set(0xc000a9d1e0, 0x1e63040, 0xc0002021e0, 0xc0012925a0, 0x5d, 0x19a4b80, 0xc0002572c0, 0x1e26f20, 0xc00036f1e0)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/storage/internal/elastic/store.go:106 +0x598
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/events.LogEntry.Register(0x1e63040, 0xc0002021e0, 0x0, 0xc0010b4060, 0x2e, 0xc000dcc030, 0xc000560af0, 0x4f, 0x50, 0xc00c52cbd3093327, ...)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/events/log_entries.go:173 +0x2a2
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/events.LogEntry.RegisterAsString(...)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/events/log_entries.go:185
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/tasks/workflow.(*worker).runWorkflowStep(0xc000b1e600, 0x1e63040, 0xc0002021e0, 0xc000aae200, 0x1bf3dbb, 0x9, 0x1, 0x1beede0, 0x6)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/tasks/workflow/worker.go:788 +0x227
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/tasks/workflow.(*worker).runUndeploy(0xc000b1e600, 0x1e63040, 0xc0002021e0, 0xc000aae200, 0xc000a36060, 0x24)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/tasks/workflow/worker.go:612 +0x1f7
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/tasks/workflow.(*worker).handleExecution(0xc000b1e600, 0xc000aae200)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/tasks/workflow/worker.go:214 +0x73a
Mar 16 16:52:14 peaalx1038 yorc: github.com/ystia/yorc/v4/tasks/workflow.(*worker).Start.func1(0xc000b1e600)
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/tasks/workflow/worker.go:83 +0x4c
Mar 16 16:52:14 peaalx1038 yorc: created by github.com/ystia/yorc/v4/tasks/workflow.(*worker).Start
Mar 16 16:52:14 peaalx1038 yorc: /var/jenkins_home/workspace/yorc/v4.0.4+premium/3@2/tasks/workflow/worker.go:75 +0x3f
```

### PR DESCRIPTION
**Pull request by SebastienLaurent**
- Fix panic when ES unreachable
  - Fix error handling in doQueryEs

### What I did

This is a bugfix in ES Store 
- Yorc no longer panic when ES become unreachable
- In some case, Error were silently discarded  in doQueryES

### How to verify it

Doing deployments while ES is shutdown

## Applicable Issues

Fixes #719

### CODE REVIEW

File: storage/internal/elastic/es_utils.go [hunk 1]
```diff
@@ -178,7 +178,7 @@ func doQueryEs(c *elasticsearch6.Client, conf elasticStoreConf,
 		c.Search.WithSort("iid:"+order),
 	)
 	if e != nil {
-		err = errors.Wrapf(err, "Failed to perform ES search on index %s, query was: <%s>, error was: %+v", index, query, err)
+		err = errors.Wrapf(e, "Failed to perform ES search on index %s, query was: <%s>, error was: %+v", index, query, err)
```
Comment (laurentganne) [inline storage/internal/elastic/es_utils.go:181]: Should use the error `e` instead of `err` as well at the end of line (last argument)

**Review by laurentganne — APPROVED** [review]
Looks good!
